# Thera Bank -- Marketing Campaign -- Model

In [1]:
# import all libraries
import pandas as pd
import numpy as np
import plotly.express as px
import pandas_profiling as pp
import seaborn as sns
import plotly.graph_objs as go#visualization
import plotly.offline as py#visualization

In [2]:
#load the dataset 
df= pd.read_csv('Bank_Personal_Loan_Modelling-1.csv')

In [3]:
# check the data on basic level
df.shape

(5000, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
ID                    5000 non-null int64
Age                   5000 non-null int64
Experience            5000 non-null int64
Income                5000 non-null int64
ZIP Code              5000 non-null int64
Family                5000 non-null int64
CCAvg                 5000 non-null float64
Education             5000 non-null int64
Mortgage              5000 non-null int64
Personal Loan         5000 non-null int64
Securities Account    5000 non-null int64
CD Account            5000 non-null int64
Online                5000 non-null int64
CreditCard            5000 non-null int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [5]:
df.describe().transpose()

count          mean          std     min       25%  \
ID                  5000.0   2500.500000  1443.520003     1.0   1250.75   
Age                 5000.0     45.338400    11.463166    23.0     35.00   
Experience          5000.0     20.104600    11.467954    -3.0     10.00   
Income              5000.0     73.774200    46.033729     8.0     39.00   
ZIP Code            5000.0  93152.503000  2121.852197  9307.0  91911.00   
Family              5000.0      2.396400     1.147663     1.0      1.00   
CCAvg               5000.0      1.937938     1.747659     0.0      0.70   
Education           5000.0      1.881000     0.839869     1.0      1.00   
Mortgage            5000.0     56.498800   101.713802     0.0      0.00   
Personal Loan       5000.0      0.096000     0.294621     0.0      0.00   
Securities Account  5000.0      0.104400     0.305809     0.0      0.00   
CD Account          5000.0      0.060400     0.238250     0.0      0.00   
Online              5000.0      0.596800     0.490589     0.0      0.00   
CreditCard          5000.0      0.294000     0.455637     0.0      0.00   

                        50%       75%      max  
ID                   2500.5   3750.25   5000.0  
Age                    45.0     55.00     67.0  
Experience             20.0     30.00     43.0  
Income                 64.0     98.00    224.0  
ZIP Code            93437.0  94608.00  96651.0  
Family                  2.0      3.00      4.0  
CCAvg                   1.5      2.50     10.0  
Education               2.0      3.00      3.0  
Mortgage                0.0    101.00    635.0  
Personal Loan           0.0      0.00      1.0  
Securities Account      0.0      0.00      1.0  
CD Account              0.0      0.00      1.0  
Online                  1.0      1.00      1.0  
CreditCard              0.0      1.00      1.0

In [7]:
# Personal Loan is our target column lets check the numbers there
df['Personal Loan'].value_counts()

0    4520
1     480
Name: Personal Loan, dtype: int64

In [31]:
##Split the train and test
from sklearn.model_selection import train_test_split
train,test = train_test_split(df,test_size = .3 ,random_state = 111)
    
##seperating dependent and independent variables
cols    = [i for i in df.columns if i not in Id_col + target_col + exclude]
X_train = train[cols]
y_train = train[target_col]
X_test = test[cols]
y_test  = test[target_col]

In [39]:
from sklearn import preprocessing
X_train=preprocessing.scale(X_train)
X_test=preprocessing.scale(X_test)

In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report,precision_score,recall_score,f1_score

from sklearn.neighbors import KNeighborsClassifier

# KNN Classifier

In [34]:
## Finding best k value

In [42]:
def knn_classifier(k):
    knn = KNeighborsClassifier(algorithm = 'auto', leaf_size = 30, metric = 'minkowski', metric_params = None, n_jobs = 1, n_neighbors = k, p = 2, weights = 'uniform')
    knn.fit(X_train, y_train)
    predictions = knn.predict(X_test)
    probabilities = knn.predict_proba(X_test)
    precision = precision_score(y_test, predictions)
    accuracy = accuracy_score(y_test, predictions)
    rs = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    print('f1_score  for k ={}  is  {}'.format(k, f1))
#     print('Accuracy score for k ={}  is  {}'.format(k, accuracy))
for k in range(1, 20, 2):
    knn_classifier(k)

f1_score  for k =1  is  0.8
f1_score  for k =3  is  0.7772925764192139
f1_score  for k =5  is  0.7692307692307692
f1_score  for k =7  is  0.7671232876712328
f1_score  for k =9  is  0.7264150943396227
f1_score  for k =11  is  0.673170731707317
f1_score  for k =13  is  0.6633663366336634
f1_score  for k =15  is  0.6633663366336634
f1_score  for k =17  is  0.6363636363636365
f1_score  for k =19  is  0.6331658291457287


In [46]:
    knn = KNeighborsClassifier(algorithm = 'auto', leaf_size = 30, metric = 'minkowski', metric_params = None, n_jobs = 1, n_neighbors = 5, p = 2, weights = 'uniform')
    knn.fit(X_train, y_train)
    predictions = knn.predict(X_test)
    probabilities = knn.predict_proba(X_test)
    precision = precision_score(y_test, predictions)
    accuracy = accuracy_score(y_test, predictions)
    rs = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    conf_mat=confusion_matrix(y_test, predictions)
    print(conf_mat)
    print (f1)

[[1364    4]
 [  47   85]]
0.7692307692307692


In [47]:
## Logistic regression
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state=1)
log_reg.fit(X_train, y_train)
predictions = log_reg.predict(X_test)
probabilities = log_reg.predict_proba(X_test)
precision = precision_score(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
rs = recall_score(y_test, predictions)
f1 = f1_score(y_test, predictions)
conf_mat=confusion_matrix(y_test, predictions)
print(classification_report(y_test, predictions))
print(f1)
print(conf_mat)

              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1368
           1       0.77      0.64      0.70       132

    accuracy                           0.95      1500
   macro avg       0.87      0.81      0.84      1500
weighted avg       0.95      0.95      0.95      1500

0.6995884773662552
[[1342   26]
 [  47   85]]


In [45]:
from sklearn.naive_bayes import GaussianNB
gb = GaussianNB()
gb.fit(X_train, y_train)
predictions = gb.predict(X_test)
probabilities = gb.predict_proba(X_test)
precision = precision_score(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
rs = recall_score(y_test, predictions)
f1 = f1_score(y_test, predictions)
conf_mat=confusion_matrix(y_test, predictions)
print(classification_report(y_test, predictions))
print(f1)
print(conf_mat)

              precision    recall  f1-score   support

           0       0.96      0.91      0.93      1368
           1       0.38      0.58      0.46       132

    accuracy                           0.88      1500
   macro avg       0.67      0.75      0.70      1500
weighted avg       0.91      0.88      0.89      1500

0.4624624624624625
[[1244  124]
 [  55   77]]
